### PR TITLE
Add support for Playstation Mouse

### PR DESCRIPTION
**Pull request by wheremyfoodat**
There's at least 1 person somewhere in the globe that wanted this
https://user-images.githubusercontent.com/44909372/156898077-f1c143fc-87e2-44b0-b993-d6834ac9b135.mp4

### CODE REVIEW

**Comment by nicolasnoble** [comment]
This looks so unusable :P Is there a way to try and make it the same coordinates as the viewport?

**Comment by wheremyfoodat** [comment]
> This looks so unusable :P Is there a way to try and make it the same coordinates as the viewport?
Nope, the PS Mouse works by just sending coordinate deltas via SIO. Then each game sets its own mouse area and does stuff.

**Comment by nicolasnoble** [comment]
Maybe having a toggle to capture the mouse completely and shoving the cursor inside the viewport at all times, only keeping the deltas for the mouse input, just like vmware and other virtualbox?

**Comment by nicolasnoble** [comment]
Maybe toggle the capture only when running?

Like, the gui object should only have an internal boolean for `enableRawMouseMotion` / `disableRawMouseMotion`, and then have something like this somewhere:

```c++
    m_listener.listen<Events::ExecutionFlow::Run>([this](const auto& event) { if (m_disableRawMouseMotion) actuallyDisableMouse(); });
    m_listener.listen<Events::ExecutionFlow::Pause>([this](const auto& event) { actuallyEnableMouse(); });
```

**Comment by nicolasnoble** [comment]
Also I don't think it's going to restore properly on config reloading?

**Review by nicolasnoble — APPROVED** [review]

**Pull request merged**
