### PR TITLE
Fix timestamps in GUI file dialogs

### PR DESCRIPTION
**Pull request by torresam**
Addresses #502 

Verified on my Windows 10 machine that:
1) The timestamps were incorrect prior to the change reproducing #502 
2) And that they were correct after this change
image

### CODE REVIEW

**Review by nicolasnoble — DISMISSED** [review]
Thanks!

**Review by nicolasnoble — DISMISSED** [review]

**Comment by nicolasnoble** [comment]
Hmmm, it sounds like Linux / MacOS builds aren't happy with it... `std::chrono::clock_cast` is supposed to be C++20, but maybe the libc++ there didn't get this feature yet? I'll try and investigate.

**Comment by torresam** [comment]
> Hmmm, it sounds like Linux / MacOS builds aren't happy with it... `std::chrono::clock_cast` is supposed to be C++20, but maybe the libc++ there didn't get this feature yet? I'll try and investigate.

Hmm it looks like it's not quite supported in libc++ yet 
https://libcxx.llvm.org/Status/Cxx20.html#cxx20-status

Should be P0355R7 I believe

**Comment by nicolasnoble** [comment]
Goddammit, I tried to be clever and shoe-horn in an implementation for clock_cast, but as much as Linux tolerates my implementation, MacOS says nay.

**Comment by nicolasnoble** [comment]
Yeah at this point, I've exhausted what I can think of to make MacOS' compiler happy.

If someone has a Mac machine and is willing to have at it, that'd be great.

**Comment by torresam** [comment]
I tested commit I just pushed on a Mac and it compiles, should work on all platforms now.
```
Software:
    System Software Overview:
      System Version: macOS 11.3.1 (20E241)
      Kernel Version: Darwin 20.4.0
```

**Comment by nicolasnoble** [comment]
How... did it even work elsewhere...?

**Review by nicolasnoble — APPROVED** [review]

**Comment by nicolasnoble** [comment]
Thanks again :)

**Pull request merged**
