### PR TITLE
Add new opcodes to psyq-obj-parser, treat functions as STT_FUNC, fix …

### PR DESCRIPTION
**Pull request by mkst**
…reloc offset

Are there any files I can/could/should test my changes against?

Managed to :ok: using psyq + these changes:

```sh
wine tools/psyq/4.6/ccpsx.exe -c -v -D_REAL_PSYQ -Iinclude -G0 -Wall -fno-builtin -O2 src/esa/3FCEC.c -o build/src/esa/3FCEC.c.obj
CCPSX 3.06.0017 (Win32, PSX version 3.02)
tools\psyq\4.6\\cpppsx -undef -D__GNUC__=2 -v -D_REAL_PSYQ -Iinclude -Wall -D__OPTIMIZE__ -lang-c -Dmips -D__mips__ -D__mips -Dpsx -D__psx__ -D__psx -D_PSYQ -D__EXTENSIONS__ -D_MIPSEL -D__CHAR_UNSIGNED__ -D_LANGUAGE_C -DLANGUAGE_C src/esa/3FCEC.c ./PQ2 
GNU CPP version 2.95.1 SN32 BUILD 4.0.0022 [AL 1.1, MM 40] Sony Playstation
#include "..." search starts here:
#include <...> search starts here:
 include
End of search list.
The following default directories have been omitted from the search path:
End of omitted list.
tools\psyq\4.6\\cc1psx -quiet -version -G0 -Wall -fno-builtin -O2 ./PQ2 -o ./PQ3 
GNU C version 2.95.2 19991024 BUILD 4.0.0030 (PSX) compiled by CC.
tools\psyq\4.6\\aspsx -q -G0 ./PQ3 -o build/src/esa/3FCEC.c.obj 
tools/psyq-obj-parser build/src/esa/3FCEC.c.obj -v -o build/src/esa/3FCEC.c.o
:: Reading signature.
 --> Signature ok.
:: Reading version: 2
:: Parsing file...
  :: Read opcode 46 --> Program type 7
  :: Read opcode 16 --> Section: id 1, group 0, alignment 8, name .rdata
  :: Read opcode 16 --> Section: id 2, group 0, alignment 8, name .text
  :: Read opcode 16 --> Section: id 3, group 0, alignment 8, name .data
  :: Read opcode 16 --> Section: id 4, group 0, alignment 8, name .sdata
  :: Read opcode 16 --> Section: id 5, group 0, alignment 8, name .sbss
  :: Read opcode 16 --> Section: id 6, group 0, alignment 8, name .bss
  :: Read opcode 16 --> Section: id 7, group 0, alignment 8, name .ctors
  :: Read opcode 16 --> Section: id 8, group 0, alignment 8, name .dtors
  :: Read opcode 28 --> File 9: Z:\esa\SRC\ESA\3FCEC.C
  :: Read opcode 6 --> Switch to section 2
  :: Read opcode 6 --> Switch to section 2
  :: Read opcode 2 --> Bytes (0094)
000000: 00 24 04 00 03 24 04 00 00 2c 05 00 03 2c 05 00  .$...$...,...,..
000010: 23 28 a4 00 00 2c 05 00 03 2c 05 00 00 34 06 00  #(...,...,...4..
000020: 04 00 a1 04 03 34 06 00 68 01 a2 24 00 14 02 00  .....4..h..$....
000030: 03 2c 02 00 03 00 a0 14 b4 00 a2 28 08 00 e0 03  .,.........(....
000040: 21 10 00 00 0b 00 40 14 23 10 a6 00 21 10 a6 00  !.....@.#...!...
000050: 68 01 42 28 05 00 40 14 68 01 02 24 23 10 45 00  h.B(..@.h..$#.E.
000060: 00 14 02 00 08 00 e0 03 03 14 02 00 08 00 e0 03  ................
000070: 21 10 c0 00 03 00 40 04 00 00 00 00 00 00 00 08  !.....@.........
000080: 23 10 06 00 23 10 05 00 00 14 02 00 08 00 e0 03  #...#...........
000090: 03 14 02 00                                      ....

  :: Read opcode 10 --> Relocation 74 (REL26), offset 007c+00000000, expression: 
    Add:
      Base of section 2
      Value: 00000060
  :: Read opcode 6 --> Switch to section 2
  :: Read opcode 60 --> SLD_END
  :: Read opcode 12 --> Export: id 10, section 2, offset 00000000, name func_8004F6EC
  :: Read opcode 74 --> FUNCTION: section 2, offset 0, _file 0, startLine 0, frameReg 29, frameSize 0, retnPcReg 31, mask 0, maskOffset 0, name func_8004F6EC
  :: Read opcode 76 --> FUNCTION_END: section 2, offset 148, endLine 0
  :: Read opcode 0 --> EOF
:: Converting build/src/esa/3FCEC.c.obj to build/src/esa/3FCEC.c.o...
  :: Generating sections
    :: Generating section .text
  :: Generating relocations - pass 1, local only
    :: Generating relocation     REL26             .text::0000007c  .text__base + 96
      :: Creating local symbol $.rel.text@00000060
  :: Generating symbols
    :: Generating symbol func_8004F6EC
  :: Generating relocations - pass 2, globals only
    :: Generating relocation     REL26             .text::0000007c  .text__base + 96
      :: Skipped for this pass
:: Conversion completed.
mips-elf-ld -EL -Map build/esa.map -T esa.ld -T undefined_syms_auto.esa.txt -T undefined_funcs_auto.esa.txt -T undefined_syms.esa.txt --no-check-sections -o build/esa.elf
mips-elf-objcopy -O binary build/esa.elf build/esa.dat
build/esa.dat: OK
```

With thanks to psxdev discord + https://github.com/Mr-Wiseguy/.

### CODE REVIEW

**Comment by mkst** [comment]
Before this gets merged, I'd like to test it against a few more functions locally 😊

**Comment by nicolasnoble** [comment]
> Before this gets merged, I'd like to test it against a few more functions locally 😊

Did you manage to get happy with the change btw? Should we move forward with it?

**Comment by mkst** [comment]
Yes please, it has all the opcodes I need - if I come across any more at a later date I can raise a new PR for them 🙂, thanks!

**Review by nicolasnoble — APPROVED** [review]

**Comment by nicolasnoble** [comment]
Cool, thanks :)

**Pull request merged**
