### PR TITLE
Fix for getButton

### LINKED ISSUE #1447: Pads getButton doesn't work
### Describe the bug

PCSX.SIO0.slots.pads.getButton returns False if the button is pressed.

### Expected behavior

It should return True (according to [this](https://pcsx-redux.consoledev.net/Lua/redux-basics/#pads))

### Steps to reproduce the bug

image

### Operating System

Ubuntu 23.04

### PCSX-Redux version

Build from source

### CPU model

.

### GPU model & Drivers

.

### BIOS version

.

### Options

- [ ] Dynarec CPU
- [ ] 8MB
- [ ] OpenGL GPU
- [ ] Fastboot
- [ ] Debugger

### Iso checks

_No response_

### Logs

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kiletic**
fixes #1447 but im not sure if it breaks something

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
This fixes this function being used with Lua overrides but completely breaks when the button is actually pressed on the keyboard or gamepad.

**Comment by wheremyfoodat** [comment]
The correct version is ((overrides & buttons) & (1 << button)) == 0

**Comment by kiletic** [comment]
Completely missed that my bad, fixed now with your suggestion

**Comment by wheremyfoodat** [comment]
Np

**Review by wheremyfoodat — APPROVED** [review]

**Pull request merged**
