### PR TITLE
Adding support for pad glyphs in the proportional font.

### LINKED ISSUE #1608: Error showing special symbols
I accidentally noticed during translation (into Ukrainian) that arrows (←↓→↑), action buttons (×■▲●) and other Unicode symbols aren't shown, they are replaced by _"?"_. Somehow I didn't pay attention to this before. Version **18254.20240303.1**.
Is it possible to support such symbols, perhaps in a separate font? If not, then I'll immediately edit the translation and type these symbols in words.
Thanks in advance.

### PR DESCRIPTION
**Pull request by nicolasnoble**
Should fix #1608.

### CODE REVIEW

**Comment by StanleyKid-22** [comment]
Does the current nightly build 18392 have this fix or should wait later?

**Comment by wheremyfoodat** [comment]
Current latest should have it

**Comment by StanleyKid-22** [comment]
I finally found a PC with Windows 10 22H2 19045.3930 and tried to run build 18521.
But cyrillic symbols, like arrows and action buttons' glyphs, are shown as "?".
Fonts are installed.

**Comment by StanleyKid-22** [comment]
[nicolasnoble](https://github.com/nicolasnoble), how's the progress? Or should I just abandon those glyphs?

**Comment by nicolasnoble** [comment]
Sorry, been really busy and juggling lots of plates. Will still get to this eventually.

**Comment by nicolasnoble** [comment]
It's fixed now.

image-29

**Pull request merged**
