### PR TITLE
Finally add support for CHD files

### PR DESCRIPTION
**Pull request by RockfordRoe**
It looks like the CHD support thing raised in #546 has never actually had a PR although it has been ready for almost a year, I'm hoping this will be taken care of once and for all.

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
Hello. This PR isn't really mergeable. The files edited in the original code don't exist anymore, having long since been refactored. The code also doesn't bring libchd which makes it uncompileable even if merge conflicts are fixed, and it doesn't follow the code style of the rest of the project either.

**Comment by lorn10** [comment]
Perhaps someone should ping @ducalex directly and ask him what the current status is on this interesting matter. :wink:

**Comment by ducalex** [comment]
> Perhaps someone should ping @ducalex directly and ask him what the current status is on this interesting matter. 😉

The code in this PR was definitely not ready to be merged. It worked (at the time) but I couldn't figure out the best way to add libchdr and lzma to the repo (i.e. bundled vs subrepository) and how to properly update the vsprojects to use it.

At this point it's probably best if someone else starts a new PR from scratch!

**Comment by lorn10** [comment]
Thanks for the clarification. So in this case it looks that this PR should be closed.:disappointed:  @wheremyfoodat

**Pull request closed without merging**
